### PR TITLE
Update to Tldraw 2.1.4, add read only view, allow embed into markdown

### PR DESCRIPTION
**Pull request by jon-dez**
- Update to Tldraw 2.1.4
- Migrate files created with Tldraw 2.0.0-alpha.14 to use 2.1.4 schema
- Add TldrawReadonly custom view
- Add button in status bar to switch to read only (RO)
- Removed patch on Tldraw package

Demo of switching to read only mode:

[Screencast from 2024-05-30 21-00-11.webm](https://github.com/holxsam/tldraw-in-obsidian/assets/48642222/160431ce-d019-4879-a209-8ad7e7aed1ce)

### CODE REVIEW

**Comment by jon-dez** [comment]
Implemented embedding a tldraw document into an obsidian markdown file.

Get the release here:
https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/tldraw-markdown-embed-2

image

**Comment by holxsam** [comment]
Hey @jon-dez, thanks for the contribution, it looks awesome! I'm a bit busy but give me a week to review it and I'll merge it and push a new version.

**Comment by jon-dez** [comment]
> Hey @jon-dez, thanks for the contribution, it looks awesome! I'm a bit busy but give me a week to review it and I'll merge it and push a new version.

No problem, take your time and thanks!

**Comment by holxsam** [comment]
All features work as intended, great job with the schema migration and the embed feature! Merged it, will create a new release version after some house keeping. Thanks again for your work :)

**Comment by seomwan** [comment]
This is worth a minor or even major release, thanks jon, and holxsam!

**Comment by jon-dez** [comment]
@holxsam @seomwan thanks!

**Pull request merged**
