### PR TITLE
feat: add save as copy in new file menu

### PR DESCRIPTION
**Pull request by cdierkens**
- Adds a new file menu
- Adds a "Save a Copy"

https://github.com/user-attachments/assets/6005ae41-5013-4bdd-9369-33b878eaeb01

### CODE REVIEW

**Comment by cdierkens** [comment]
Closes https://github.com/holxsam/tldraw-in-obsidian/issues/27

**Comment by jon-dez** [comment]
I can confirm this works as intended.

**Comment by visualcode** [comment]
Any news for this feature?

**Comment by jon-dez** [comment]
@visualcode Yes, this feature will be included in a new release shortly so stay tuned!

**Comment by jon-dez** [comment]
@cdierkens This PR will be closed. But have no fear, PR #33 will be merged to main and this commit is included in that PR!

**Comment by visualcode** [comment]
Great! Thanks. Is the open .tld file also included in the feature?

**Comment by cdierkens** [comment]
@jon-dez thanks!

@visualcode I did not include the import feature in this PR. This update was only exporting.

The path forward should be very similar, and should be pretty straightforward.

**Pull request closed without merging**
